"""log rights assistant runs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 14:34:33.374035
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('dropped_citations', sa.Integer(), nullable=False),
    sa.CheckConstraint("mode IN ('ai', 'demo', 'off')", name='assistant_runs_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('assistant_runs_created_at', 'assistant_runs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('assistant_runs_created_at', table_name='assistant_runs')
    op.drop_table('assistant_runs')
    # ### end Alembic commands ###
